# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 53e6919460e55c93677dc8c9f6a0056f09c350c0deff10e3c1618fcdd1c028bf9803b0c31f158efbb76d01e3ea62a90133b1b0684476d4d714c3b07e3a4e8b73

test:
  secret_key_base: 719d7113d8a667aac47f90d4866b6d6707c015fc6b99ea9aed434e0ded1f0b3d12be133265c9040e536610098eabe6a219e8eaad5bd9d5cea8ffd5c98eedecd7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
